/** Build-time contract for the module generated by OpenNext. */
declare module '*/.open-next/worker.js' {
  import type { CloudflareContext } from '@opennextjs/cloudflare';

  const handler: {
    fetch(
      request: Request,
      env: CloudflareContext['env'],
      ctx: CloudflareContext['ctx'],
    ): Promise<Response>;
  };

  export default handler;
}
