compatibility_date = "2026-03-04"
compatibility_flags = [
  "global_fetch_strictly_public",
  "nodejs_compat",
]
main = ".open-next/worker.js"
name = "scsys-io-www"
workers_dev = true

[build]
command = "opennextjs-cloudflare build"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability.logs]
enabled = true

[images]
binding = "IMAGES"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "scsys-io-www"

[vars]
NEXT_PUBLIC_SITE_URL = "https://scsys.io"
NEXT_PUBLIC_SUPABASE_URL = "https://gilqgzjkzkmhbbcqidqb.supabase.co"
NEXT_TELEMETRY_DISABLED = 1
NODE_ENV = "production"
NODE_VERSION = 24

[[routes]]
custom_domain = true
pattern = "scsys.io"
zone_id = "scsys.io"
