name: NodeJS

concurrency:   
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  NEXT_TELEMTRY_DISABLED: 1
  NODE_VERSION: 24

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, reopened, synchronize ]
  push:
    branches: [ main, master ]
    tags: [ v*.*.*, "*-alpha", "*-beta", "*-canary", "*-nightly" ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ node ]

permissions:
  contents: read
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - 
        name: Install Dependencies
        run: npm ci
      - 
        name: Build for CloudFlare
        run: npm run cf:build
  