name: 'Copilot Setup Steps'

# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  workflow_dispatch:
    inputs:
      bun-version:
        default: 'latest'
        description: 'Bun version'
        required: true
        type: string
      target:
        description: 'Target triple to benchmark for'
        required: true
        default: 'wasm32-unknown-unknown'
        type: choice
        options:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
          - wasm32-wasip1
          - wasm32-wasip2
      toolchain:
        default: stable
        description: 'Select a toolchain to test (stable, nightly, beta)'
        required: true
        type: choice
        options: [stable, nightly, beta]

# environment variables available to all jobs and steps
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  NEXT_TELEMETRY_DISABLED: 1
  NODE_ENV: production
# permissions enabled for all jobs
permissions:
  contents: read
# the ci jobs to run
jobs:
  setup:
    name: 'Copilot Setup Steps'
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: build
      BUN_VERSION: latest
      RUST_TOOLCHAIN: ${{ github.event.inputs.toolchain || 'stable' }}
      CARGO_TARGET: ${{ github.event.inputs.target || 'x86_64-unknown-linux-gnu' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Setup the Cache
        id: cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.bun/install/cache
            apps/myfi/${{ env.BUILD_DIR }}/cache
            apps/tips/${{ env.BUILD_DIR }}/cache
          # Generate a new cache whenever packages or source files change.
          key: bun-${{ runner.os }}-${{ hashFiles('**/*.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            bun-${{ runner.os }}-${{ hashFiles('**/*.lock') }}-
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          target: ${{ env.CARGO_TARGET }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - name: Setup additional cargo tools
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack
      - name: Install dependencies
        run: bun install
      - name: Build the workspace
        run: bun run build
